### ISSUE TITLE
ST_ClusterDBSCAN Feature Request

### ISSUE THREAD

**Issue by cjtexas** [apache/sedona#1546]
I am interested in seeing [ST_ClusterDBSCAN](https://postgis.net/docs/ST_ClusterDBSCAN.html) in Sedona SQL. Thanks!

**Comment by jiayuasu** [comment]
We will push a native DBSCAN function on Sedona in a few weeks. Stay tuned!

**Comment by zwu-net** [comment]
> We will push a native DBSCAN function on Sedona in a few weeks. Stay tuned!

It will be great to have this implemented. However, it must be cautious. A few years ago, I used this library https://elki-project.github.io/. I believed I read an article  by some creators of this library that many implementations of this clustering algorithm are incorrect. Since the test results of the cases are indetermined (i.e.  the same input you can get different correct results, or different incorrect results) .  I'll update this comment if I can find the article I read before.

**Comment by jiayuasu** [comment]
Note that there is a PR to add DBSCAN function to Sedona Scala and Python (not SQL) interfaces: https://github.com/apache/sedona/pull/1589

**Comment by james-willis** [comment]
>  the test results of the cases are indetermined

Theres some argument about whether DBSCAN is deterministic. I would argue that determinism isnt super important in DBSCAN and the case in which indeterminism arises is practically quite rare.

However, the implementation I've put up is deterministic. Interested to hear any feedback about determinism in my implementation if you have any.

**Comment by zwu-net** [comment]
> > the test results of the cases are indetermined
> 
> Theres some argument about whether DBSCAN is deterministic. I would argue that determinism isnt super important in DBSCAN and the case in which indeterminism arises is practically quite rare.
> 
> However, the implementation I've put up is deterministic. Interested to hear any feedback about determinism in my implementation if you have any.

I'm fine with an implementation that doesn't strictly adhere to academic definitions of indeterminism. As long as it's practical and effective, I think it is fine. Any potential arguments against this approach will likely come from an academic perspective, which we may not need to care much.
