### ISSUE TITLE
setup.py out of sync with Pipfile

### ISSUE THREAD

**Issue by joaofauvel** [apache/sedona#1607]
Pipfile pins numpy<2, but setup.py does not list numpy as a dependency, which may cause numpy>2 to be installed, leading to hard to debug issues in different environments, such as Databricks.
Discussions [here](github.com/pypa/pipenv/issues/1263) and [docs](https://docs.pipenv.org/advanced/#pipfile-vs-setup-py) have some information as to best practices of keeping setup.py and Pipfile in sync.

## Expected behavior
`pip install apache-sedona`
numpy<2 installed

## Actual behavior
`pip install apache-sedona`
numpy>2 installed

## Steps to reproduce the problem
Install pypi's apache-sedona package on a clean environment.

## Settings

Sedona version = 1.6.1

Apache Spark version = NA

Apache Flink version = NA

API type = Python

Scala version = NA

JRE version = NA

Python version = NA

Environment = NA

**Comment by joaofauvel** [comment]
In Databricks, the following error is logged in driver logs stderr if sedona python is installed as a cluster library.
```
Traceback (most recent call last):
  File "/databricks/python_shell/scripts/db_ipykernel_launcher.py", line 21, in <module>
    from dbruntime.DatasetInfo import UserNamespaceCommandHook, UserNamespaceDict
  File "/databricks/python_shell/dbruntime/DatasetInfo.py", line 10, in <module>
    from pyspark.sql.connect.dataframe import DataFrame as ConnectDataFrame
  File "/databricks/spark/python/pyspark/sql/connect/dataframe.py", line 26, in <module>
    check_dependencies(__name__)
  File "/databricks/spark/python/pyspark/sql/connect/utils.py", line 36, in check_dependencies
    require_minimum_pandas_version()
  File "/databricks/spark/python/pyspark/sql/pandas/utils.py", line 29, in require_minimum_pandas_version
    import pandas
  File "/databricks/python/lib/python3.11/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/databricks/python/lib/python3.11/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/databricks/python/lib/python3.11/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/databricks/python/lib/python3.11/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/databricks/python/lib/python3.11/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

If the user installs sedona in the notebook then sedona will run but will result in all sorts of issues or kernel crashes.

If installed as a cluster library, any code will result in 
```
Failure starting repl. Try detaching and re-attaching the notebook.
```

DBR ML 15 or lower installs ydata-profiling 4.5.1 (indirectly depends on numpy 1.23.x), however sedona's dependency rasterio 1.4.0 released yesterday now requires numpy >=1.24, which should cause sedona's installation to fail but doesn't due to pip and the fact that numpy<2 is not in sedona's setup.py. As a result latest numpy gets installed and issues or crashes in Databricks due to numpy 2 being incompatible with pandas version required by DBR ML 15 or lower.  
Workaround is to install rasterio<1.4.0 before installing sedona.

**Comment by Kontinuation** [comment]
The Pipfile in the sedona repository is for setting up an environment for running tests, not enforcing the dependency versions when installing the `apache-sedona` package on users' environments. The dependency requirement of sedona is quite loose since it wants to pose fewer restrictions on users' Python environment. The non-optional dependencies are the following 3 items:

* attrs
* shapely>=1.7.0
* rasterio>=1.2.10

The optional dependency requirements also have no restrictions on the version of pandas or geopandas. The versions of transitive dependencies are meant to be resolved by the package manager or the user. Unfortunately, [pandas 1.5.3 requires numpy>=1.21.0](https://github.com/pandas-dev/pandas/blob/v1.5.3/setup.cfg#L34-L37), which makes numpy 2 a version satisfying the requirement, so numpy 2 was picked up when installing rasterio using `pip`.

We can add `numpy < 2` and constraints to other packages such as `pandas <= 1.5.3` to setup.py to fix this failure on DBR, but it poses unnecessary restrictions to the user's python environment. For instance, the usage of sedona package on python environments with numpy 2 and pandas 2.2 installed.

**Comment by joaofauvel** [comment]
I wasn't sure where to make this issue, but I agree constraining numpy will lead to unnecessary restrictions to the user, as it's just a transitive dependency of the python wrapper. Still, anyone working in Databricks with `apache-sedona` will experience this, as such it may warrant some documentation beyond a closed issue.

**Comment by Sarwat** [comment]
Joao, you make good points. May you please prepare a PR to fix the
documentation.

Thanks,
-
