### ISSUE TITLE
Adapter.toDf converts polygon to string

### ISSUE THREAD

**Issue by thekannman** [apache/sedona#176]
I am trying to take the shapefile from [here](https://www.census.gov/geo/maps-data/data/cbf/cbf_state.html) and make a dataframe for use with geospark-sql.

```    
scala> var spatialRDD = new SpatialRDD[Geometry]
scala> spatialRDD.rawSpatialRDD = ShapefileReader.readToGeometryRDD(spark.sparkContext, "cb_2016_us_state_500k")
scala> val spatialDFNoSchema = Adapter.toDf(spatialRDD,spark)
```

The spatialRDD has the correct type:
```
scala> spatialRDD
res312: org.datasyslab.geospark.spatialRDD.SpatialRDD[com.vividsolutions.jts.geom.Geometry] = org.datasyslab.geospark.spatialRDD.SpatialRDD@6c1b02f9
```
However, using the adapter function as suggested [here](https://github.com/DataSystemsLab/GeoSpark/wiki/GeoSparkSQL-Constructor) results in a dataframe where the polygons (the rddshape field) are strings instead.
```
scala> Adapter.toDf(spatialRDD,spark)
res313: org.apache.spark.sql.DataFrame = [rddshape: string, _c1: string ... 8 more fields]
```

Is there any way to get a dataframe with the polygons maintaining their type? If not, is it possible to use the string representation in the st_contains function?

**Comment by jiayuasu** [comment]
Hi @thekannman ,

Yes, this Adapter just simply convert shapefile geometry to WKT string. I cannot directly change it to Geometry type DataFrame because Spark currently makes UserDefinedType inaccessible from the outside world.

However, GeoSpark 1.0 provides a constructor for you to easily convert WKT string to geometry DataFrame.

Once you got your "val spatialDFNoSchema = Adapter.toDf(spatialRDD,spark)"
The remaining part is is like this:
```
spatialDFNoSchema.createOrReplaceTempView("rawSpatialDf")
var spatialDF = spark.sql("SELECT ST_GeomFromWKT(rddshape), _c1,_c2,_c3
FROM rawSpatialDf")
spatialDF.printSchema
```

This will create a geometry type column and can be directly used in GeoSparkSQL.

The related document is here: https://github.com/DataSystemsLab/GeoSpark/wiki/GeoSparkSQL-Constructor

**Comment by thekannman** [comment]
Ah, fantastic. Thank you!
