### ISSUE TITLE
Tune SQL join query performance and handle Exception: Number of partitions>=0

### ISSUE THREAD

**Issue by SrinivasRIL** [apache/sedona#218]
## Expected behavior
I am doing a simple ST_Contains query to check whether points lie within the polygon.  I have created two seperate dataframes for points and polygon using shapefile as an input for both. I am using zeppelin notebook 
## Actual behavior
when I perform this query
var Containsdf = sparkSession.sql("select * from polydf, pointdf where ST_Contains(polydf.shape,pointdf.shape)")
Containsdf.show()

I get the following messages and error

Containsdf: org.apache.spark.sql.DataFrame = [shape: geometry, shape: geometry]
root
 |-- shape: geometry (nullable = false) 
 |-- shape: geometry (nullable = false)
**java.lang.IllegalArgumentException: Number of partitions must be >= 0**

I also set geospark.join.numpartition as 1 while declaring the spark session

Since I am new to spark, i am following the tutorials for geosparksql but I am not a sure  why I am getting this error. Kindly help...

## Settings

GeoSpark version = 1.1

Apache Spark version =2.1 

JRE version = 1.8.051

API type = Scala

**Comment by jiayuasu** [comment]
@SrinivasRIL I guess you are using GeoSpark 1.1.0. This is a known bug in GeoSpark 1.1.0 and earlier. Please use GeoSpark 1.1.2 instead.

Please read 1.1.2 release notes: http://datasystemslab.github.io/GeoSpark/download/GeoSpark-All-Modules-Release-notes/

**Comment by jiayuasu** [comment]
@SrinivasRIL 

Spatial join query is complex so it needs some parameter tuning.

1. Did you open GeoSpark kryo serializer? If not, please open it. This will affect the join performance a lot.
2. GeoSparkSQL will build quad tree index on-the-fly for spatial join. You don't need to load RDD index into DataFrame.
GeoSparkSQL has several [parameters](http://datasystemslab.github.io/GeoSpark/api/sql/GeoSparkSQL-Parameter/). Use the following code to change the default partitioning method to KDBtree, this will improve the join performance.
```
sparkSession = SparkSession.builder().
      config("spark.serializer",classOf[KryoSerializer].getName).
      config("spark.kryo.registrator", classOf[GeoSparkKryoRegistrator].getName).
      config("geospark.join.gridtype","kdbtree")
      master("local[*]").appName("myGeoSparkSQLdemo").getOrCreate()
```
3. Try to swap ST_Intersects(polygons, points) to ST_Intersects(points, polygons). This will affect the performance sometimes. The result is still accurate.

4. Try to repartition the dataframe used in the left side of ST_Intersects operator to more partitions. For example, double the number of partitions.

5. How many candidate pairs do you expect to have? Since you have 30k polygons and 10k points, will they all intersect each other? If so, it is slow for sure. Because you are generating a table which has over 1 billion pairs.

**Comment by jiayuasu** [comment]
@SrinivasRIL 

That's great! 
1. In general, the new partition numbers should be around 2~3 times more than its original partitions. Too many partitions will decrease the join speed because Spark needs to manage too many partition info and communicate with workers.
2. Storing the entire DataFrame including all columns to disk is as easy as this:

CSV file:
```
df.write.csv("/Users/jiayu/Downloads/testspark")
```
Parquet file:
```
df.write.save("/Users/jiayu/Downloads/testspark")
```
Note that: the geometry column is stored as WKT String format. When you load the DataFrame back, you need to use "ST_GeomFromWKT" to recover the geometry type.

3. We do have a ST_Buffer function, namely ST_Circle. This will create a buffer around the center object (point, polygon, linestring). See [ST_Circle](http://datasystemslab.github.io/GeoSpark/api/sql/GeoSparkSQL-Constructor/#st_circle) to learn. I know the name is not a Spatial SQL standard name so we will change it to ST_buffer in the next release

**Comment by Bhavesh-Joshi** [comment]
@jiayuasu

Hii, I am facing similar problem **java.lang.IllegalArgumentException: [GeoSpark] Number of partitions 1 cannot be larger than half of total records num 1**, When I am trying to perform simple ST_Contains operation of two datasets, one dataset having only one polygon as record and other having 2 points. I am using following:

- GeoSpark version = 1.1.3
- Apache Spark version =2.2.0
- JRE version = 1.8.051
- API type = Java

SQL Query: 
**select polygonDataset.polygon, pointDataset.point from polygonDataset,pointDataset where ST_Contains(ST_GeomFromWKT(polygonDataset.polygon),ST_GeomFromWKT(pointDataset.point))**

Refer following links to access polygon and point dataset:
[https://gist.github.com/Bhavesh-Joshi/591c5f1802cc2c2e26d4a605494913de#file-point-csv](point.csv)
[https://gist.github.com/Bhavesh-Joshi/5c2f738cad397250f041b0960c3e1358](polygon.csv)

**Comment by jiayuasu** [comment]
@Bhavesh-Joshi GeoSpark cannot work with a Dataframe which has only 1 object.
Df partitions should be no larger than 0.5*numObjects. So, if there is only 1 object, no way for GeoSpark to do spatial partitioning.

**Comment by Bhavesh-Joshi** [comment]
@jiayuasu
Please suggest your work around for doing these.

**Comment by jiayuasu** [comment]
@Bhavesh-Joshi 

Use more test data, at least 2 polygons. Not just 1 polygon in a DF.

**Comment by bdgeise** [comment]
@jiayuasu - It's possible in our use cases that we might only have 1 polygon that needs to be run against our data.  Is there a suggested workaround besides duplicating the polygon?

**Comment by jiayuasu** [comment]
@Bhavesh-Joshi We will add the optimizer strategy for this situation. For now, if you find the input polygon set only has one polygon, you need to use SpatialRangeQuery. See an example here: http://datasystemslab.github.io/GeoSpark/tutorial/rdd/#write-a-spatial-range-query

You can easily convert between SpatialRDD and SpatialDataFrame: http://datasystemslab.github.io/GeoSpark/tutorial/sql/#convert-between-dataframe-and-spatialrdd

**Comment by bdgeise** [comment]
@jiayuasu - Thanks.  What's the easiest way to convert the result from a RangeQuery to dataframe?

**Comment by jiayuasu** [comment]
@Bhavesh-Joshi 

```
var spatialRDD = new SpatialRDD[Geometry]()
spatialRDD.rawSpatialRDD = SpatialRangeQuery(queryPolygon,inputSpatialRDD,...)
spatialRDD.fieldNames = inputSpatialRDD.fieldNames
var spatialDf = Adapter.toDf(spatialRDD, sparkSession)
```

**Comment by viswanatharv** [comment]
@SrinivasRIL 

Thanks for asking the question. I am also facing different issues dealing with AWS Instances.

Can you please let me know the Hardware configuration and sample code you have tried for **ST_Contains** to achieve 30 Billion transactions (3 Lacks Polygons and 1 Lack Points) in 1.5 minutes.

Awaiting for your response...

Thanks
Vis...

**Comment by dbilid** [comment]
Hello, are there any news on this? 

Actually where does the restriction that Df partitions should be no larger than 0.5*numObjects comes from? I just tested this by modifying RDDSampleUtils.getSampleNumbers to return 1 in case totalNumberOfRecords=1 and it seems to work correctly, but as I am not familiar with the internals of GeoSpark I do not know side-effectes this may have.

thanks,
Dimitris
