### ISSUE TITLE
move dependency to locationtech JTS

### ISSUE THREAD

**Issue by geoHeil** [apache/sedona#233]
`com.vividsolutions.jts` will continue further development at https://github.com/locationtech/jts. Geospark should consider moving to that library.

**Comment by geoHeil** [comment]
Gettos 0.20.x was just released. They already migrated to the new location tech JTS. As Geospark is based on both JTS and geotools one should strongly consider this upgrade in both JTS and geotools.

**Comment by geoHeil** [comment]
This would probably require to move / port functionality from https://github.com/jiayuasu/JTSplus over to the new JTS https://github.com/locationtech/jts

**Comment by jiayuasu** [comment]
@geoHeil I believe there are some code that JTS folks won't allow. For instance, see this commit:https://github.com/jiayuasu/JTSplus/commit/f3d71e5fcdc8f0971595b580805d27a8f76e2e88. In order to write a spatial index serializer, we have to change some function scopes from private to public. We also added some functions to return the leaf node boundaries of indexes.

Currently, I think there is no reason JTS will need these changes.

I want to use the latest JTS but still want to keep our changes.

**Comment by geoHeil** [comment]
you mean it might be better if the underlying dependency of JTSplus will be swapped?
