### ISSUE TITLE
Save spatial index for further usage

### ISSUE THREAD

**Issue by seamusdu** [apache/sedona#35]
I've gone through the code and I'm not sure whether I understand it right or not. It seems to me that the spatial index is not supported to be saved for further reuse at this stage. Currently, I would like to save the index to HDFS integrated with the dataset so that I don't need to generate the spatial index every time I try to use the dataset.  Could you please give me some suggestions or probably I misunderstand the function. 

Thanks.

**Comment by jiayuasu** [comment]
Hi @seamusdu ,

You understand the code correctly. GeoSpark builds small local indexes on each RDD partition (each partition has a small index). Currently, we don't save index onto disk because we assume that people will build the index once, cache it into memory and re-use it many times. Actually, this initialization is relatively fast (I have tested on large datasets) because we build local R-Tree indexes in parallel.

But, I agree with you. Storing the index onto disk is a feature which is good to have. We will consider this.

Thanks,
Jia Yu

**Comment by jiayuasu** [comment]
GeoSpark spatial index can be persisted onto permanent storage using .SaveAsObjectFile. It can also be reused later on. The spatial index and its internal geometries are all serializable.
 
On the other hand, we are seeking an efficient customized serialization method to minimize the index in-memory size, although GeoSpark customized geometry serializer already did some work.

**Comment by jiayuasu** [comment]
@zongsizhang Let's try to release this function in GeoSpark 1.1.0. We may mark the unsolved performance issue as "experimental".

**Comment by pedromorfeu** [comment]
@jiayuasu, I'm trying to save a huge indexed RDD to file using `saveAsObjectFile(path)`, but it fails with Java heap space error. I can get rid of it by increasing the heap space with `-Xmx`, but it seems that the RDD isn't partitioned because it persists all the data in a single file. As saving a partitioned RDD isn't recommended, what can I do?

**Comment by pedromorfeu** [comment]
Is it safe, then, to repartition the indexed RDD before saving? As in:
```
shapesRDD.indexedRawRDD.repartition(10).saveAsObjectFile(outputFile)
```

**Comment by jiayuasu** [comment]
@pedromorfeu Please repartition the RDD right after you create the SpatialRDD. before you build index. Because in the indexedRDD, each partition is an index. Repartitioning indexedRDD won't work.

**Comment by pedromorfeu** [comment]
Like this?:
```
shapesRDD.rawSpatialRDD.repartition(10)
```

**Comment by jiayuasu** [comment]
@pedromorfeu Yes. Later on, the indexed spatialrdd will inherit this partition num.
