### ISSUE TITLE
[Question] Recommendations for buildIndex and spatialPartitioning

### ISSUE THREAD

**Issue by pedromorfeu** [apache/sedona#355]
@Question
Are there any recommendations for choosing the best side to build index and partition when performing a join query? 

For instance: if I have a big and a small SpatialRDDs, which one should be indexed (`buildIndex`)? And which one should I partition (`spatialPartitioning`)?

GeoSpark version = 1.2.0
Apache Spark version = 2.3.0
JRE version = 1.8
API type = Scala

**Comment by jiayuasu** [comment]
@pedromorfeu  (1) Please always use the big RDD as the first spatial partitioning RDD. This will lead to a more balanced spatial partition grid file (2) Please always build index on the big RDD. This will significantly speed up the join query. Because the local join complexity (on each partition pair) is O(M*log(N)) . M is the cardinality of the small RDD partition and N is the cardinality of the big RDD partition.
