### ISSUE TITLE
Range Query Performance

### ISSUE THREAD

**Issue by AntreasPetsas** [apache/sedona#388]
Hello there.
I am trying to find out how geospark doing the Range Query.

Suppose we have a dataset partitioned by an Equal Partitioner in 4 grids.
Also suppose we have a range window that give us results only from grid no1 of our partitioner. This means (obviously) that range window is covered by grid no1(ONLY).
So here is my question. I put some "println" and i get in conclusion that geospark is checking every spatial object in every grid to find out which spatial objects are covered by range window. Is this the correct approach of range Query?
I thought that Geospark should only check every spatial object only from grid no 1. That was my first approach before looking at the code.

Any ideas? Should i implement my approach by my one? or am i looking in the wrong place?

**Comment by jiayuasu** [comment]
@AntreasPetsas You are right. Currently, GeoSpark passes the query window to all partitions in the query window. GeoSpark range query does not require spatial partitioning and cannot be run on spatial partitioned rdd. This is for the sake of range performance.


Another way to do it is, (1) spatial partitioned the Spatial RDD, (2) find useless partition by checking range query window against the partition tree, (3) filter useless partition by calling RDD API rdd.PartitionPruningRDD, (4) then perform the range query on the selected RDD partition, (5) finally do duplicate removal to guarantee the accuracy.

GeoSpark currently does not implement the second approach because I really don't know whether it will be really faster than the first approach.

**Comment by AntreasPetsas** [comment]
Thank you @jiayuasu for the quick reply.

So, you are telling me that geospark does not use the structure of a R-tree(STRtree) to partition, and the do range query properly? I mean, if an internal node is not covered by or intersected by the range window, then you do not need to check its leaves(or its internal nodes). But geospark check them all right?
Can the same approach you mentioned above be applied for Rtree partitioning?
What if i change the source code and not just use the existing methods?

(sorry for my english btw) :) :)
