### ISSUE TITLE
geo_pyspark in AWS Glue

### ISSUE THREAD

**Issue by pabloginerwind** [apache/sedona#407]
Has anyone used these libraries within Glue?
Thanks!

## Expected behavior
Can run Glue jobs using the GeoSpark functions

## Actual behavior
Unable to import

## Steps to reproduce the problem
In a Development Endpoint, with the JARs added during creation, try to `from geo_pyspark.register import GeoSparkRegistrator`

## Settings

GeoSpark version = latest

Apache Spark version = 2.4

JRE version = 1.8?

API type =

**Comment by Imbruced** [comment]
Hi,
I have never used GeoSpark (Python or Scala API) in AWS Glue. What kind of error did you get ? ModuleNotFoundError ? Did you install package from wheel file or using setup.py ?

**Comment by pabloginerwind** [comment]
Hi!
Correct, I get ModuleNotFoundError. Glue is serverless, so I cannot install anything. What I can do is to add the required jar files, which I did by adding the 2.4 files.

**Comment by Imbruced** [comment]
Did you try this tutorial <a href="https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-libraries.html"> link </a> ? According to the link, you have to zip the package, you can try with wheel file extension <b> python/dist/geo_pyspark-0.2.0-py3-none-any.whl </b> instead of zip (wheel file is an archive). If it will not work you can try to zip the package.

**Comment by pabloginerwind** [comment]
Hello! Apparently it will not work unless it is a pure python library... I will keep researching and also try to get help from AWS.

**Comment by Imbruced** [comment]
I will also try to figure it out (some spare time during the winter break). In addition, SpatialRDD API for Python should be available soon.
