### ISSUE TITLE
Load and save SpatialRDD

### ISSUE THREAD

**Issue by Tsarazin** [apache/sedona#51]
Hi guys, 
I would like to know what is the best way to save and load a PointRDD, PolygonRDD, RectangleRDD? I have big datasets containing geopoints and I don't want to create a PointRDD and index it everytime I need to do a match with another dataset. I want to create a PointRDD and save it in my HDFS. Something as 
val p = new PointRDD()
p.save("path")

**Comment by jiayuasu** [comment]
Hi @Tsarazin ,

Thanks for pointing this out. Saving the indexed spatial RDD on disk needs a proper R-Tree / Quad-Tree serialization and deserialization method. I am implementing it into JTSplus (not GeoSpark core) but haven't finished yet. Will try to finish it as soon as possible.

Thanks,
Jia

**Comment by kanghq** [comment]
That's a fantastic feature if it is possible to convert from JTS element RDD to Spatial RDD as well as R-Tree/Quad-Tree index support.

**Comment by netanel246** [comment]
I tried to save and load SpatialRDD and I didn't succeed with the load phase:

```
// Save
geojsonRDD.rawSpatialRDD.saveAsObjectFile("/tmp/genericRDD");

// Load - not compiled because objectFile recived RDD[T] and not SpatialRDD[T]
val genericRDD = sc.objectFile[SpatialRDD[Geometry]]("/tmp/genericRDD")
```

I have succeeded to save and load a spatial index, but it will be useful if we can also save and load a SpatialRDD, because in our case we need to spatial join two "layers", which one of them is static, and there is no sense in creating this SpatailRDD for each run.
