### ISSUE TITLE
/src/test/resources/modis/modis.csv doesn't exist

### ISSUE THREAD

**Issue by hyoklee** [apache/sedona#784]
I want to test `core/src/main/scala/org/apache/sedona/core/showcase/ScalaEarthdataMapperRunnableExample.scala`.

## Expected behavior

Test file `modis.csv` exists.

## Actual behavior

Both release and GitHub repo don't have the `modis.csv` file.

## Steps to reproduce the problem

Download the release or git clone the repo.

## Settings

Sedona version = 1.3.1

Apache Spark version = 3.3.2

API type = Scala

Scala version = 2.12

JRE version = 1.8

Environment = Standalone

**Comment by jiayuasu** [comment]
We intend to remove it due to its large size in the source code. We plan to have a neat implementation of NetCDF reader soon. Anyway, you can find it in the past release: https://github.com/apache/sedona/releases/tag/sedona-1.0.0-incubating

Download "source code (zip)" or tarball, you will find it.

**Comment by hyoklee** [comment]
Does "a neat implementation of NetCDF reader" mean a brand new Java/Scala implementation or using n upgrade version (e.g., 6.0) of the existing necdf-java package?
Anyway, I can't wait to see the new netCDF implementation in Sedona!
Thank you for working hard to support netCDF and HDF.

**Comment by jiayuasu** [comment]
We plan to have something similar to Sedona GeoTiff reader: https://github.com/apache/sedona/blob/master/sql/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala#L252

RS_FromNetCDF
