### ISSUE TITLE
[DOCS] Provide clarity on how Apache Sedona deals with different CRS when joining rasters/vectors

### ISSUE THREAD

**Issue by jornfranke** [apache/sedona#941]
## Expected behavior
I have for example in the documentation a part which provides an example on how to join a raster with a vector dataset (cf. https://sedona.apache.org/1.4.1/api/sql/Raster-operators/#rs_values). 

However, it is not clear to me how the case of different CRS is handled, e.g. not-at-all or automatic conversion (to which one?)
This is also not clear for the case raster to raster join.

I propose to have a page on joining vector/vector, raster/raster and raster/vector join and how to deal with different CRS (possibly also linking here: https://sedona.apache.org/1.4.1/api/sql/Optimizer/). 

I can try to draft a page if you can give a small pointer to the code?

## Actual behavior

How different CRS can be handled when joining data is described.

## Steps to reproduce the problem

It is just a documentation problem.

## Settings

Sedona version = 1.4.1

Apache Spark version = ?

Apache Flink version = ?

API type = Scala, Java, Python?

Scala version =  2.12

JRE version = 1.8, 1.11?

Python version = 3.9

Environment = all

**Comment by ashutosh887** [comment]
Let me work on this

**Comment by jornfranke** [comment]
I am not deciding this, but I guess if you propose a merge request that contains the documentation on this then this will be accepted.

I can help you also, I have applied Sedona for those cases. However, of course the one that implemented the functionality in Sedona can provide more insights.

**Comment by jornfranke** [comment]
From my experience, for the rasters it looks like Sedona reads the metadata from the Geotiff file:
* [RS_FromGeoTiff](https://sedona.apache.org/1.4.1/api/sql/Raster-loader/#rs_fromgeotiff)

Question: Is this correct (if yes => document it)? What are the limitations? eg. what metadata it cannot interpret (=> document it)

For the vectors it depends:
* [ST_GeomFromWKT](https://sedona.apache.org/1.4.1/api/sql/Constructor/#st_geomfromwkt). Here it is unclear what is the default [srid](https://en.wikipedia.org/wiki/Spatial_reference_system)? Also the documentation should contain a reference to the wikipedia article: https://en.wikipedia.org/wiki/Spatial_reference_system 
* [ST_GeomFromGeoJSON](https://sedona.apache.org/1.4.1/api/sql/Constructor/#st_geomfromgeojson): I assume it reads the CRS from the geojson file (if correct then document it) and what happens if it is not defined in the geojson?

I believe if we can document those aspects then a lot of users will benefit (especially those that are more new to geospatial coding)

**Comment by Kontinuation** [comment]
`RS_FromGeoTiff` reads CRS metadata from the GeoTiff file, and the resulting raster value will have that CRS property. You can retrieve the EPSG code of the CRS using `RS_SRID` (if it has one).

`RS_FromGeoTiff` is using GeoTools GeoTiff reader under the hood. However, I've not found any documentation describing the limitation of GeoTools GeoTiff reader. The limitation I am aware of is that it does not support user defined Model CRS type (GTModelTypeGeoKey = 32767, see [Requirements Class GTModelTypeGeoKey](https://docs.ogc.org/is/19-008r4/19-008r4.html#_requirements_class_gtmodeltypegeokey)).

For vector data, the default SRID is 0, which indicates that the geometry does not have a defined CRS. `ST_GeomFromGeoJSON` does not support parsing the crs member in GeoJSON, and the resulting geometries always have SRID = 0.

SRID is the EPSG code of coordinate reference systems. The CRS is forced to easting/northing or lon/lat axis order since https://github.com/apache/sedona/pull/963, which will be released with 1.5.0. For any released versions of Apache Sedona, the CRS uses the original axis order defined by EPSG.

I think explicitly documenting the behaviors related to CRS would be beneficial. As we integrate raster support into Apache Sedona, this aspect is gaining increasing significance.

**Comment by jiayuasu** [comment]
@jornfranke Sedona 1.5.0 raster and vector join will perform implicit CRS transformation: https://sedona.apache.org/1.5.0/api/sql/Raster-operators/#raster-predicates

Rules for testing spatial relationship:

If the raster or geometry does not have a defined SRID, it is assumed to be in WGS84.
If both sides are in the same CRS, then perform the relationship test directly.
Otherwise, both sides will be transformed to WGS84 before the relationship test.
